eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  tomcat: 
    access-log-enabled: true
    access-log-pattern: ${spring.application.name}|1|%a|%A|%t|%m|%D|%s|%U|%q
logging: 
  path: /Users/davidwu/logs
  file: ${spring.application.name}.log



domain: dev.163.com

spring: 
  datasource: 
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://127.0.0.1:3306/jeesite?useUnicode=true&characterEncoding=utf8  
    username: root  
    password: 123456  
    driver-class-name: com.mysql.jdbc.Driver  
    minIdle: 1  
    maxActive: 2  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false 

  redis: 
    host: localhost
    password:
    port: 6379 
    pool:
      max-idle: 100 
      min-idle: 1
      max-active: 1000
      max-wait: -1